name: penguinator-cli
base: core22
version: '0.1'
summary: A CLI client for Azure Image Testing for Linux API
description: |
  Azure Image Testing for Linux Client is a light CLI client for the Azure Image Testing for Linux API

  https://penguinatorstarter.powerappsportals.com/webapis2/

license: GPL-3.0
contact: cpc@canonical.com
website: https://github.com/canonical/penguinator-cli
issues: https://github.com/canonical/penguinator-cli/issues

grade: stable
confinement: strict

parts:
  penguinator-cli:
    plugin: python
    source: .
    python-packages:
      - pip
      - setuptools
      - wheel
      - '.'

apps:
  penguinator-cli:
    command: bin/penguinator-cli
    plugs:
      - network
